# Generated by Django 6.0.8 on 2026-08-30 17:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('public_key', models.CharField(max_length=43, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('agent_version', models.CharField(blank=True, max_length=64)),
                ('protocol_version', models.CharField(blank=True, max_length=16)),
                ('provider_capabilities', models.JSONField(default=list)),
                ('capabilities_reported_at', models.DateTimeField(blank=True, null=True)),
                ('control_interval_seconds', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)])),
                ('reported_control_interval_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('run_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.SlugField(max_length=128)),
                ('provider_version', models.CharField(max_length=64)),
                ('contract_version', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=16)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('datasets', models.JSONField(default=list)),
                ('scope', models.JSONField(default=list)),
                ('messages', models.JSONField(default=list)),
                ('completeness_token', models.CharField(blank=True, max_length=512)),
                ('payload_digest', models.CharField(max_length=64)),
                ('observation_count', models.PositiveIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='netbox_ssot.collectoragent')),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_payload_digest', models.CharField(max_length=64)),
                ('target_snapshot_digest', models.CharField(max_length=64)),
                ('engine_version', models.CharField(max_length=32)),
                ('direction', models.CharField(default='source_to_target', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('create_count', models.PositiveIntegerField(default=0)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('no_change_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons', to='netbox_ssot.collectionrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=16)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, max_length=1000)),
                ('decision_digest', models.CharField(editable=False, max_length=64)),
                ('approved_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comparison', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_review', to='netbox_ssot.comparisonrun')),
            ],
            options={
                'ordering': ('-reviewed_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True)),
                ('collection_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comparison_preparation', to='netbox_ssot.collectionrun')),
                ('comparison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparations', to='netbox_ssot.comparisonrun')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=16)),
                ('resource_kind', models.CharField(max_length=64)),
                ('identity_key', models.CharField(max_length=1024)),
                ('display_name', models.CharField(max_length=512)),
                ('source_external_id', models.CharField(max_length=512)),
                ('target_object_type', models.CharField(blank=True, max_length=128)),
                ('target_object_id', models.CharField(blank=True, max_length=128)),
                ('match_basis', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('source_data', models.JSONField(default=dict)),
                ('target_data', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=list)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='netbox_ssot.comparisonrun')),
            ],
            options={
                'ordering': ('comparison_id', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='ApplyRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(default='source_to_target', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('create_count', models.PositiveIntegerField(default=0)),
                ('update_count', models.PositiveIntegerField(default=0)),
                ('no_change_count', models.PositiveIntegerField(default=0)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comparison', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='apply_run', to='netbox_ssot.comparisonrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DiscoverySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('provider_id', models.SlugField(max_length=128)),
                ('configuration', models.JSONField(default=dict)),
                ('datasets', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('collection_interval_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(43200)])),
                ('retention_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('retention_successful_runs', models.PositiveIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('retention_failure_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('active_collection_started_at', models.DateTimeField(blank=True, null=True)),
                ('active_collection_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='netbox_ssot.collectoragent')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='netbox_ssot.discoverysource'),
        ),
        migrations.CreateModel(
            name='AgentEnrollmentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_prefix', models.CharField(editable=False, max_length=20)),
                ('agent_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolled_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='netbox_ssot.collectoragent')),
                ('target_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replacement_enrollment_tokens', to='netbox_ssot.collectoragent')),
                ('sources', models.ManyToManyField(blank=True, related_name='agent_enrollment_tokens', to='netbox_ssot.discoverysource')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('state', models.CharField(default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('reporting_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='netbox_ssot.collectoragent')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='netbox_ssot.discoverysource')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='ObjectBinding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_kind', models.CharField(max_length=64)),
                ('source_external_id', models.CharField(max_length=512)),
                ('identity_key', models.CharField(max_length=1024)),
                ('target_object_type', models.CharField(max_length=128)),
                ('target_object_id', models.CharField(max_length=128)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_applied_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='netbox_ssot.applyrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_bindings', to='netbox_ssot.discoverysource')),
            ],
            options={
                'ordering': ('source_id', 'resource_kind', 'source_external_id'),
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=16)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, max_length=1000)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='netbox_ssot.comparisonrun')),
                ('comparison_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='netbox_ssot.comparisonitem')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('comparison_id', 'comparison_item_id', 'decided_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StoredObservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('resource_kind', models.CharField(max_length=64)),
                ('external_id', models.CharField(max_length=512)),
                ('collected_at', models.DateTimeField()),
                ('scope', models.JSONField(default=list)),
                ('attributes', models.JSONField(default=list)),
                ('relationships', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('fingerprint', models.CharField(max_length=64)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stored_observations', to='netbox_ssot.collectionrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='netbox_ssot.discoverysource')),
            ],
            options={
                'ordering': ('run_id', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='AgentSigningKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=43, unique=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('state', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('retire_after', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_keys', to='netbox_ssot.collectoragent')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['agent', 'state'], name='ssot_agent_key_state_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('agent',), name='ssot_agent_one_active_key_uniq')],
            },
        ),
        migrations.CreateModel(
            name='AgentSecurityEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='netbox_ssot.collectoragent')),
            ],
            options={
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['agent', '-occurred_at'], name='ssot_agent_security_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplyItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=16)),
                ('resource_kind', models.CharField(max_length=64)),
                ('source_external_id', models.CharField(max_length=512)),
                ('target_object_type', models.CharField(max_length=128)),
                ('target_object_id', models.CharField(max_length=128)),
                ('apply_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='netbox_ssot.applyrun')),
                ('comparison_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='apply_item', to='netbox_ssot.comparisonitem')),
            ],
            options={
                'ordering': ('apply_run_id', 'sequence'),
                'indexes': [models.Index(fields=['apply_run', 'action'], name='ssot_apply_item_action_idx'), models.Index(fields=['apply_run', 'resource_kind'], name='ssot_apply_item_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('apply_run', 'sequence'), name='ssot_apply_item_sequence_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='comparisonrun',
            index=models.Index(fields=['collection_run', '-created_at'], name='ssot_cmp_collection_idx'),
        ),
        migrations.AddConstraint(
            model_name='comparisonrun',
            constraint=models.UniqueConstraint(fields=('collection_run', 'target_snapshot_digest', 'engine_version', 'direction'), name='ssot_comparison_run_target_uniq'),
        ),
        migrations.AddIndex(
            model_name='comparisonreview',
            index=models.Index(fields=['decision', '-reviewed_at'], name='ssot_review_state_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonpreparation',
            index=models.Index(fields=['state', '-updated_at'], name='ssot_cmp_prep_state_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonitem',
            index=models.Index(fields=['comparison', 'action'], name='ssot_cmp_item_action_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonitem',
            index=models.Index(fields=['comparison', 'resource_kind'], name='ssot_cmp_item_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='comparisonitem',
            constraint=models.UniqueConstraint(fields=('comparison', 'sequence'), name='ssot_comparison_item_sequence_uniq'),
        ),
        migrations.AddIndex(
            model_name='collectionrun',
            index=models.Index(fields=['source', '-completed_at'], name='ssot_run_source_done_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrun',
            index=models.Index(fields=['provider_id', 'state'], name='ssot_run_provider_state_idx'),
        ),
        migrations.AddIndex(
            model_name='agentenrollmenttoken',
            index=models.Index(fields=['token_hash', 'expires_at'], name='ssot_enroll_token_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentenrollmenttoken',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('target_agent__isnull', False), ('used_at__isnull', True)), fields=('target_agent',), name='ssot_agent_one_replacement_uniq'),
        ),
        migrations.AddIndex(
            model_name='agentcommand',
            index=models.Index(fields=['agent', 'state', 'requested_at'], name='ssot_command_agent_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentcommand',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('pending', 'dispatched', 'running', 'reporting'))), fields=('source', 'kind'), name='ssot_command_source_kind_active_uniq'),
        ),
        migrations.AddIndex(
            model_name='objectbinding',
            index=models.Index(fields=['source', 'target_object_type', 'target_object_id'], name='ssot_binding_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='objectbinding',
            constraint=models.UniqueConstraint(fields=('source', 'resource_kind', 'source_external_id'), name='ssot_binding_source_object_uniq'),
        ),
        migrations.AddIndex(
            model_name='reviewdecision',
            index=models.Index(fields=['comparison', 'comparison_item', '-decided_at', '-id'], name='ssot_review_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='storedobservation',
            index=models.Index(fields=['source', 'resource_kind', 'external_id'], name='ssot_obs_source_identity_idx'),
        ),
        migrations.AddConstraint(
            model_name='storedobservation',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='ssot_observation_run_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='storedobservation',
            constraint=models.UniqueConstraint(fields=('run', 'resource_kind', 'external_id'), name='ssot_observation_identity_uniq'),
        ),
    ]
