# Generated by Django 5.2.12 on 2026-08-28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscoverySource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("provider_id", models.SlugField(max_length=128)),
                ("configuration", models.JSONField(default=dict)),
                ("datasets", models.JSONField(default=list)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="CollectorAgent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("public_key", models.CharField(max_length=43, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sources",
                    models.ManyToManyField(blank=True, related_name="agents", to="netbox_ssot.discoverysource"),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="CollectionRun",
            fields=[
                ("run_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("provider_id", models.SlugField(max_length=128)),
                ("provider_version", models.CharField(max_length=64)),
                ("contract_version", models.CharField(max_length=32)),
                ("state", models.CharField(max_length=16)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("datasets", models.JSONField(default=list)),
                ("scope", models.JSONField(default=list)),
                ("messages", models.JSONField(default=list)),
                ("completeness_token", models.CharField(blank=True, max_length=512)),
                ("payload_digest", models.CharField(max_length=64)),
                ("observation_count", models.PositiveIntegerField()),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="netbox_ssot.collectoragent",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="netbox_ssot.discoverysource",
                    ),
                ),
            ],
            options={"ordering": ("-received_at",)},
        ),
        migrations.CreateModel(
            name="StoredObservation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sequence", models.PositiveIntegerField()),
                ("resource_kind", models.CharField(max_length=64)),
                ("external_id", models.CharField(max_length=512)),
                ("collected_at", models.DateTimeField()),
                ("scope", models.JSONField(default=list)),
                ("attributes", models.JSONField(default=list)),
                ("relationships", models.JSONField(default=list)),
                ("evidence", models.JSONField(default=list)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stored_observations",
                        to="netbox_ssot.collectionrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="netbox_ssot.discoverysource",
                    ),
                ),
            ],
            options={"ordering": ("run_id", "sequence")},
        ),
        migrations.AddIndex(
            model_name="collectionrun",
            index=models.Index(fields=["source", "-completed_at"], name="ssot_run_source_done_idx"),
        ),
        migrations.AddIndex(
            model_name="collectionrun",
            index=models.Index(fields=["provider_id", "state"], name="ssot_run_provider_state_idx"),
        ),
        migrations.AddIndex(
            model_name="storedobservation",
            index=models.Index(
                fields=["source", "resource_kind", "external_id"],
                name="ssot_obs_source_identity_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedobservation",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"),
                name="ssot_observation_run_sequence_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedobservation",
            constraint=models.UniqueConstraint(
                fields=("run", "resource_kind", "external_id"),
                name="ssot_observation_identity_uniq",
            ),
        ),
    ]
