# Generated by Django 6.0.8 on 2026-08-28 12:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_payload_digest", models.CharField(max_length=64)),
                ("target_snapshot_digest", models.CharField(max_length=64)),
                ("engine_version", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("create_count", models.PositiveIntegerField(default=0)),
                ("update_count", models.PositiveIntegerField(default=0)),
                ("no_change_count", models.PositiveIntegerField(default=0)),
                ("conflict_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                (
                    "collection_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comparisons",
                        to="netbox_ssot.collectionrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ComparisonItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sequence", models.PositiveIntegerField()),
                ("action", models.CharField(max_length=16)),
                ("resource_kind", models.CharField(max_length=64)),
                ("identity_key", models.CharField(max_length=1024)),
                ("display_name", models.CharField(max_length=512)),
                ("source_external_id", models.CharField(max_length=512)),
                ("target_object_type", models.CharField(blank=True, max_length=128)),
                ("target_object_id", models.CharField(blank=True, max_length=128)),
                ("match_basis", models.CharField(max_length=64)),
                ("reason", models.TextField(blank=True)),
                ("source_data", models.JSONField(default=dict)),
                ("target_data", models.JSONField(default=dict)),
                ("changes", models.JSONField(default=list)),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="netbox_ssot.comparisonrun",
                    ),
                ),
            ],
            options={
                "ordering": ("comparison_id", "sequence"),
            },
        ),
        migrations.AddIndex(
            model_name="comparisonrun",
            index=models.Index(fields=["collection_run", "-created_at"], name="ssot_cmp_collection_idx"),
        ),
        migrations.AddConstraint(
            model_name="comparisonrun",
            constraint=models.UniqueConstraint(
                fields=("collection_run", "target_snapshot_digest"),
                name="ssot_comparison_run_target_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="comparisonitem",
            index=models.Index(fields=["comparison", "action"], name="ssot_cmp_item_action_idx"),
        ),
        migrations.AddIndex(
            model_name="comparisonitem",
            index=models.Index(fields=["comparison", "resource_kind"], name="ssot_cmp_item_kind_idx"),
        ),
        migrations.AddConstraint(
            model_name="comparisonitem",
            constraint=models.UniqueConstraint(
                fields=("comparison", "sequence"),
                name="ssot_comparison_item_sequence_uniq",
            ),
        ),
    ]
