# Generated by Django 6.0.8 on 2026-08-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssot", "0002_comparisonrun_comparisonitem_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comparisonrun",
            name="ssot_comparison_run_target_uniq",
        ),
        migrations.AddConstraint(
            model_name="comparisonrun",
            constraint=models.UniqueConstraint(
                fields=("collection_run", "target_snapshot_digest", "engine_version"),
                name="ssot_comparison_run_target_uniq",
            ),
        ),
    ]
