# Generated by Django 6.0.8 on 2026-08-28 13:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssot", "0003_remove_comparisonrun_ssot_comparison_run_target_uniq_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("create_count", models.PositiveIntegerField(default=0)),
                ("update_count", models.PositiveIntegerField(default=0)),
                ("no_change_count", models.PositiveIntegerField(default=0)),
                (
                    "applied_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "comparison",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apply_run",
                        to="netbox_ssot.comparisonrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ApplyItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("sequence", models.PositiveIntegerField()),
                ("action", models.CharField(max_length=16)),
                ("resource_kind", models.CharField(max_length=64)),
                ("source_external_id", models.CharField(max_length=512)),
                ("target_object_type", models.CharField(max_length=128)),
                ("target_object_id", models.CharField(max_length=128)),
                (
                    "comparison_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apply_item",
                        to="netbox_ssot.comparisonitem",
                    ),
                ),
                (
                    "apply_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="items", to="netbox_ssot.applyrun"
                    ),
                ),
            ],
            options={
                "ordering": ("apply_run_id", "sequence"),
                "indexes": [
                    models.Index(fields=["apply_run", "action"], name="ssot_apply_item_action_idx"),
                    models.Index(fields=["apply_run", "resource_kind"], name="ssot_apply_item_kind_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("apply_run", "sequence"), name="ssot_apply_item_sequence_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="ObjectBinding",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("resource_kind", models.CharField(max_length=64)),
                ("source_external_id", models.CharField(max_length=512)),
                ("identity_key", models.CharField(max_length=1024)),
                ("target_object_type", models.CharField(max_length=128)),
                ("target_object_id", models.CharField(max_length=128)),
                ("source_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_applied_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="bindings", to="netbox_ssot.applyrun"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="object_bindings",
                        to="netbox_ssot.discoverysource",
                    ),
                ),
            ],
            options={
                "ordering": ("source_id", "resource_kind", "source_external_id"),
                "indexes": [
                    models.Index(
                        fields=["source", "target_object_type", "target_object_id"], name="ssot_binding_target_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "resource_kind", "source_external_id"), name="ssot_binding_source_object_uniq"
                    )
                ],
            },
        ),
    ]
