# Generated by Django 6.0.8 on 2026-08-28 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_ssot", "0009_agent_command_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoverysource",
            name="retention_days",
            field=models.PositiveIntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3650),
                ],
            ),
        ),
        migrations.AddField(
            model_name="discoverysource",
            name="retention_failure_days",
            field=models.PositiveIntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3650),
                ],
            ),
        ),
        migrations.AddField(
            model_name="discoverysource",
            name="retention_successful_runs",
            field=models.PositiveIntegerField(
                default=10000,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
    ]
