# Generated by Django 6.0.8 on 2026-08-28 17:16

import base64
import hashlib
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_existing_agent_keys(apps, schema_editor):
    collector_agent = apps.get_model("netbox_ssot", "CollectorAgent")
    signing_key = apps.get_model("netbox_ssot", "AgentSigningKey")
    for agent in collector_agent.objects.iterator():
        public_key_bytes = base64.urlsafe_b64decode(agent.public_key + "=")
        signing_key.objects.create(
            agent_id=agent.pk,
            public_key=agent.public_key,
            fingerprint=hashlib.sha256(public_key_bytes).hexdigest(),
            activated_at=agent.created_at,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssot", "0010_discoverysource_retention_days_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentEnrollmentToken",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("token_prefix", models.CharField(editable=False, max_length=20)),
                ("agent_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "enrolled_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollment_tokens",
                        to="netbox_ssot.collectoragent",
                    ),
                ),
                (
                    "sources",
                    models.ManyToManyField(
                        blank=True, related_name="agent_enrollment_tokens", to="netbox_ssot.discoverysource"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["token_hash", "expires_at"], name="ssot_enroll_token_idx")],
            },
        ),
        migrations.CreateModel(
            name="AgentSecurityEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=32)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="security_events",
                        to="netbox_ssot.collectoragent",
                    ),
                ),
            ],
            options={
                "ordering": ("-occurred_at",),
                "indexes": [models.Index(fields=["agent", "-occurred_at"], name="ssot_agent_security_idx")],
            },
        ),
        migrations.CreateModel(
            name="AgentSigningKey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("public_key", models.CharField(max_length=43, unique=True)),
                ("fingerprint", models.CharField(editable=False, max_length=64, unique=True)),
                ("state", models.CharField(default="active", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("retire_after", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signing_keys",
                        to="netbox_ssot.collectoragent",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["agent", "state"], name="ssot_agent_key_state_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state", "active")),
                        fields=("agent",),
                        name="ssot_agent_one_active_key_uniq",
                    )
                ],
            },
        ),
        migrations.RunPython(migrate_existing_agent_keys, migrations.RunPython.noop),
    ]
