# Generated by Django 6.0.8 on 2026-08-28 19:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_netbox_capability(apps, schema_editor):
    collector_agent = apps.get_model("netbox_ssot", "CollectorAgent")
    for agent in collector_agent.objects.iterator():
        agent.provider_capabilities = [
            {
                "provider_id": "netbox",
                "implementation_version": "0.0.2",
                "contract_version": "1.0",
            }
        ]
        agent.capabilities_reported_at = agent.last_seen_at or agent.created_at
        agent.save(update_fields=("provider_capabilities", "capabilities_reported_at"))


def clear_backfilled_capability(apps, schema_editor):
    collector_agent = apps.get_model("netbox_ssot", "CollectorAgent")
    collector_agent.objects.update(provider_capabilities=[], capabilities_reported_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssot", "0011_agentenrollmenttoken_agentsecurityevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentenrollmenttoken",
            name="target_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacement_enrollment_tokens",
                to="netbox_ssot.collectoragent",
            ),
        ),
        migrations.AddField(
            model_name="collectoragent",
            name="capabilities_reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collectoragent",
            name="provider_capabilities",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(backfill_netbox_capability, clear_backfilled_capability),
    ]
