# Generated by Django 6.0.8 on 2026-08-28 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssot", "0012_agentenrollmenttoken_target_agent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="agentenrollmenttoken",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("revoked_at__isnull", True), ("target_agent__isnull", False), ("used_at__isnull", True)
                ),
                fields=("target_agent",),
                name="ssot_agent_one_replacement_uniq",
            ),
        ),
    ]
