# Generated by Django 6.0.8 on 2026-08-29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssot", "0013_agentenrollmenttoken_ssot_agent_one_replacement_uniq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "decision",
                    models.CharField(choices=[("approved", "Approved"), ("rejected", "Rejected")], max_length=16),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, max_length=1000)),
                ("decision_digest", models.CharField(editable=False, max_length=64)),
                ("approved_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                (
                    "comparison",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="final_review",
                        to="netbox_ssot.comparisonrun",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-reviewed_at",),
                "indexes": [models.Index(fields=["decision", "-reviewed_at"], name="ssot_review_state_idx")],
            },
        ),
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("decision", models.CharField(choices=[("approve", "Approve"), ("reject", "Reject")], max_length=16)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True, max_length=1000)),
                (
                    "comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="netbox_ssot.comparisonrun",
                    ),
                ),
                (
                    "comparison_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_decisions",
                        to="netbox_ssot.comparisonitem",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("comparison_id", "comparison_item_id", "decided_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["comparison", "comparison_item", "-decided_at", "-id"],
                        name="ssot_review_latest_idx",
                    )
                ],
            },
        ),
    ]
