# Generated by Django 6.0.8 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssot", "0014_comparisonreview_reviewdecision"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparisonrun",
            name="direction",
            field=models.CharField(
                choices=[("source_to_target", "Source to target"), ("target_to_source", "Target to source")],
                default="source_to_target",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="applyrun",
            name="direction",
            field=models.CharField(
                choices=[("source_to_target", "Source to target"), ("target_to_source", "Target to source")],
                default="source_to_target",
                max_length=32,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="comparisonrun",
            name="ssot_comparison_run_target_uniq",
        ),
        migrations.AddConstraint(
            model_name="comparisonrun",
            constraint=models.UniqueConstraint(
                fields=("collection_run", "target_snapshot_digest", "engine_version", "direction"),
                name="ssot_comparison_run_target_uniq",
            ),
        ),
    ]
