# Generated by Django 6.0.8 on 2026-08-30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ssot", "0015_synchronization_direction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComparisonPreparation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Queued"),
                            ("running", "Preparing"),
                            ("completed", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("job_id", models.UUIDField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error", models.TextField(blank=True)),
                (
                    "collection_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comparison_preparation",
                        to="netbox_ssot.collectionrun",
                    ),
                ),
                (
                    "comparison",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preparations",
                        to="netbox_ssot.comparisonrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at",),
                "indexes": [models.Index(fields=["state", "-updated_at"], name="ssot_cmp_prep_state_idx")],
            },
        ),
    ]
